### ISSUE TITLE
Git URL could allow any commit'ish, not just branches

### ISSUE THREAD

**Issue by pyrtsa** [mietek/bashmenot#12]
It would be nice to use an exact tagged version or a commit SHA-1 when appending to a Git URL. For example, a commit of Bashmenot could be pointed to by the URL https://github.com/mietek/bashmenot#08977d6 (or the full SHA-1).

The code here would seem to support doing so already: https://github.com/mietek/bashmenot/blob/08977d6382019433390f605796e92ab0876436a7/src/git.sh#L76

But this line will need a bit of adjustment to allow any commit-like identifier to be used: https://github.com/mietek/bashmenot/blob/08977d6382019433390f605796e92ab0876436a7/src/git.sh#L105

**Comment by mietek** [comment]
Thanks. I agree.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
